# Generated by Django 5.0.6 on 2024-06-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='contenu',
            field=models.TextField(verbose_name='Text_Publication'),
        ),
    ]
