# Generated by Django 5.0.6 on 2024-07-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_publications_date_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='date_publication',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
