# Generated by Django 5.0.6 on 2024-07-08 14:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_publications_date_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='contenu',
            field=ckeditor.fields.RichTextField(verbose_name='Text_Publication'),
        ),
    ]
