# Generated by Django 5.0.6 on 2024-06-22 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=9)),
                ('address', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=10)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_depart', models.DateTimeField()),
                ('date_arrivee', models.DateTimeField()),
                ('lieu_depart', models.CharField(max_length=100)),
                ('lieu_arrivee', models.CharField(max_length=100)),
                ('nombre_sieges', models.PositiveIntegerField()),
                ('numero_bus', models.CharField(max_length=20)),
                ('statut_reservation', models.CharField(choices=[('CONFIRMED', 'Confirmée'), ('PENDING', 'En attente'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=10)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservation.client')),
            ],
        ),
    ]
