# Generated by Django 5.0.6 on 2024-06-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='client',
            new_name='employer',
        ),
        migrations.AddField(
            model_name='client',
            name='nom',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='prenom',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
    ]
