# Generated by Django 5.0.6 on 2024-06-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0002_rename_client_reservations_employer_client_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='utilisateur',
        ),
    ]
