# Generated by Django 5.0.6 on 2024-06-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0004_client_utilisateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='employer',
            new_name='client',
        ),
    ]
