# Generated by Django 5.0.6 on 2024-07-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0006_alter_client_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nif',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
