# Generated by Django 5.0.6 on 2024-07-08 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0008_remove_reservations_mode_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(5000)]),
        ),
    ]
