# Generated by Django 5.0.6 on 2024-07-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0009_alter_reservations_montant_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='numero_bus',
            field=models.CharField(max_length=3),
        ),
    ]
