# Generated by Django 5.0.6 on 2024-07-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0011_alter_reservations_numero_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=8),
        ),
    ]
