# Generated by Django 5.0.6 on 2024-07-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0012_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='numero_bus',
            field=models.CharField(choices=[('1689', '1689'), ('0129', '0129'), ('1189', '1189')], default='1689', max_length=10),
        ),
    ]
