# Generated by Django 5.0.6 on 2024-07-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0013_alter_reservations_numero_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='nombre_sieges',
        ),
        migrations.AlterField(
            model_name='reservations',
            name='numero_bus',
            field=models.CharField(max_length=4),
        ),
    ]
